### PR TITLE
Adds support for OPS and adds Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by JhonathanLepidus**
Greetings

We're sending this pull request with two contributions we think would be very relevant to this plugin.

The first one is the support to be shown in the preprint view page, in OPS. In our tests, the plugin had a good functioning in OPS either in the sidebar as in the footer. However, it did not work in the preprint view page.

The second one is a translation for Brazilian Portuguese, which could improve the plugin's adoption by more sites.

Please send us feedback on these changes.

### CODE REVIEW

**Review by ronste — APPROVED** [review]

**Review by ronste — CHANGES_REQUESTED** [review]
Hi Jhonathan,

thank's for your contribution. Highly appreciated!

For this commit I would suggest to change "submission" in the string below to "publication". In the end it is published content displayed there. Would you agree?

Ronald

msgid "plugins.generic.shariff.settings.position.submission"
msgstr "submission page"

**Review by ronste — APPROVED** [review]

**Review by ronste — COMMENTED** [review]
Unfortunately I am not able to accept this commit. Maintenance of this javascript file is not our responsibility. We only use release versions from the original repo at:

https://github.com/heiseonline/shariff

We do not apply changes to external releases since they would be lost with the next update.
Maybe you could submit your changes to heiseonline instead.

Best wishes,
Ronald

**Comment by JhonathanLepidus** [comment]
Hi Ronald

I replaced the use of "submission" by "publication", as you suggested.

I also removed the changes for the javascript file. It wasn't crucial for this PR, since the most important changes are in locale files and in ShariffPlugin class.

Best wishes,
Jhonathan

**Comment by JhonathanLepidus** [comment]
Thanks!

**Pull request merged**
